#!/bin/sh
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/g/geany/geany-common_1.23.1+dfsg-1_all.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/g/geany/geany_1.23.1+dfsg-1_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/g/gnome-themes-standard/gnome-themes-standard-data_3.10.0-1ubuntu2_all.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/g/gnome-themes-standard/gnome-themes-standard_3.10.0-1ubuntu2_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/v/vlc/vlc-plugin-notify_2.1.6-0ubuntu14.04.2_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/v/vlc/vlc-nox_2.1.6-0ubuntu14.04.2_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/v/vlc/vlc_2.1.6-0ubuntu14.04.2_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/v/vlc/vlc-data_2.1.6-0ubuntu14.04.2_all.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/v/vlc/vlc-plugin-pulse_2.1.6-0ubuntu14.04.2_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/multiverse/a/atari800/atari800_3.0.0-1ubuntu2_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/c/clipit/clipit_1.4.2-1ubuntu1_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/c/conky/conky_1.9.0-4_all.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/f/fortune-mod/fortune-mod_1.99.1-7_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/f/fortune-mod/fortunes-min_1.99.1-7_all.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/g/geany-plugins/geany-plugin-codenav_1.23+dfsg-3_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/g/geany-plugins/geany-plugin-debugger_1.23+dfsg-3_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/g/geany-plugins/geany-plugin-devhelp_1.23+dfsg-3_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/g/geany-plugins/geany-plugins-common_1.23+dfsg-3_all.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/g/geany-plugins/geany-plugin-doc_1.23+dfsg-3_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/g/geany-plugins/geany-plugin-prettyprinter_1.23+dfsg-3_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/g/geany-plugins/geany-plugin-treebrowser_1.23+dfsg-3_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/g/geany-plugins/geany-plugin-updatechecker_1.23+dfsg-3_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/g/geany-plugins/geany-plugin-vc_1.23+dfsg-3_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/g/get-iplayer/get-iplayer_2.83-1_all.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/g/gnome-backgrounds/gnome-backgrounds_3.12.0-1_all.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/g/gnome-do/gnome-do_0.9-1ubuntu0.1_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/g/gnome-do-plugins/gnome-do-plugins_0.8.5-2ubuntu0.1_all.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/g/gnome-documents/gnome-documents_3.10.2-0ubuntu1_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/g/gnome-hearts/gnome-hearts_0.3-2.1ubuntu1_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/g/gnome-shell/gnome-shell-common_3.10.4-0ubuntu5.2_all.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/g/gnome-shell/gnome-shell_3.10.4-0ubuntu5.2_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/g/gnome-shell-extensions/gnome-shell-extensions_3.10.1-0ubuntu2_all.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/g/gnome-tweak-tool/gnome-tweak-tool_3.10.1-2ubuntu1_all.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/g/gnome-video-effects/gnome-video-effects-extra_0.4.1-0ubuntu1_all.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/g/gnome-video-effects/gnome-video-effects-frei0r_0.4.1-0ubuntu1_all.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/g/grhino/grhino-data_0.16.1-3_all.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/g/grhino/grhino_0.16.1-3_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/h/htop/htop_1.0.2-3_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/i/icoutils/icoutils_0.31.0-2_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/i/iftop/iftop_1.0~pre2-5_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/i/ipython/ipython_1.2.1-2_all.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/m/menu/menu_2.1.46ubuntu1_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/n/nautilus-open-terminal/nautilus-open-terminal_0.20-1_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/n/nestopia/nestopia_1.45+dfsg-1_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/n/nethack/nethack-common_3.4.3-14_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/n/nethack/nethack-x11_3.4.3-14_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/n/network-manager-openvpn/network-manager-openvpn_0.9.8.2-1ubuntu4_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/p/pong2/pong2_0.1.3-1_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/p/putty/putty-tools_0.63-4ubuntu0.1_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/p/pychess/pychess_0.12~beta3-1_all.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/c/chardet-whl/python-chardet-whl_2.2.1-2~ubuntu1_all.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/p/python-colorama/python-colorama_0.2.5-0.1ubuntu2_all.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/p/python-colorama/python-colorama-whl_0.2.5-0.1ubuntu2_all.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/d/distlib/python-distlib_0.1.8-1ubuntu1_all.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/d/distlib/python-distlib-whl_0.1.8-1ubuntu1_all.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/p/pyenchant/python-enchant_1.6.5-2build1_all.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/p/pygtksourceview/python-gtksourceview2_2.10.1-2build1_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/k/keybinder/python-keybinder_0.3.0-2_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/p/python-mpd/python-mpd_0.3.0-4_all.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/p/python-pip/python-pip_1.5.4-1ubuntu4_all.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/p/python-pip/python-pip-whl_1.5.4-1ubuntu4_all.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/p/python-support/python-support_1.0.15_all.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/s/sl/sl_3.03-17_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/s/synaptic/synaptic_0.81.1ubuntu1_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/s/system-tools-backends/system-tools-backends_2.10.2-1ubuntu1.14.04.1_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/k/kde-workspace/systemsettings_4.11.11-0ubuntu0.2_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/t/tango-icon-theme/tango-icon-theme_0.8.90-5ubuntu1_all.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/t/terminator/terminator_0.97-2ubuntu0.1_all.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/t/testdisk/testdisk_6.14-2_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/t/traceroute/traceroute_2.0.20-0ubuntu0.1_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/u/ubuntu-gnome-default-settings/ubuntu-gnome-default-settings_14.04.1_all.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/u/ubuntu-gnome-meta/ubuntu-gnome-desktop_0.32_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/u/ubuntu-gnome-wallpapers/ubuntu-gnome-wallpapers_14.04.1_all.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/u/ubuntu-gnome-wallpapers/ubuntu-gnome-wallpapers-trusty_14.04.1_all.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/multiverse/v/virtualbox/virtualbox-qt_4.3.36-dfsg-1+deb8u1ubuntu1.14.04.1_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/x/xjokes/xjokes_1.0-14_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/e/emacs-chess/emacs-chess_2.0b6-1.1ubuntu1_all.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/g/gnome-sushi/gnome-sushi_3.11.90-0ubuntu1_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/g/gnome-system-tools/gnome-system-tools_3.0.0-3ubuntu4.1_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/c/compiz/python-compizconfig_0.9.11.3+14.04.20160425-0ubuntu1_amd64.deb
wget -c http://gb.archive.ubuntu.com/ubuntu/pool/universe/x/xpuzzles/xmpuzzles_7.7.1-1_amd64.deb
